# This is a basic workflow to help you get started with Actions

name: Actions Tests

on:
  push:
    branches: [ github_actions_test ]
  pull_request:
    branches: [ github_actions_test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: drawio-export-${{ github.ref }}
  cancel-in-progress: true

jobs:
  render_tests:
    runs-on: ubuntu-latest
    name: Render draw.io files
    steps:
      - uses: actions/checkout@v2
      - name: Initiating entanglment
        run: echo Building Quantum Stack!

      # png
      - name: Building png
        uses: Burnett01/actions-drawio@1.1
        with:
          src: quantum_roadmap.drawio
          dest: quantum_roadmap.png
      #svg
      - name: Building svg
        uses: Burnett01/actions-drawio@1.1
        with:
          src: quantum_roadmap.drawio
          dest: quantum_roadmap.svg

    # Upload files to repo
     - name: List & upload rendered files
       run: 'ls -l ${{ steps.render.outputs.rendered-files }}'
     - uses: stefanzweifel/git-auto-commit-action@v4
       with:
         commit_message: "[Bot] Updated png!"
         commit_user_name: PMF Github Bot
         commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
         commit_author: PMF Github Bot

      # Upload Artifacts
      - name: Upload png as artifact
        uses: actions/upload-artifact@v1
        with:
          name: png
          path: quantum_roadmap.png

      - name: Upload svg as artifact
        uses: actions/upload-artifact@v1
        with:
          name: svg
          path: quantum_roadmap.svg

      - name: Collapsing Quantum states
        run: echo Finished workflow!
