# This is a basic workflow to help you get started with Actions

name: Actions Tests

on:
  push:
    branches: [ github_actions_test ]
  pull_request:
    branches: [ github_actions_test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: drawio-export-${{ github.ref }}
  cancel-in-progress: true

jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Export drawio files to asciidoctor and png files
        uses: rlespinasse/drawio-export-action@v2.x
        with:
          format: pg, pdf, png, svg, vsdx, xml
          transparent: true
          output: images

      - name: Get author and committer info from HEAD commit
        uses: rlespinasse/git-commit-data-action@v1.x
        if: github.ref == 'refs/heads/github_actions_test'

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: sync draw.io exported files"
          commit_user_name: "pmf-github-action"
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: "${{ env.GIT_COMMIT_AUTHOR }}"
        if: github.ref == 'refs/heads/github_actions_test'
