# This is a basic workflow to help you get started with Actions
# Based on: https://github.com/racklet/render-drawio-action

name: Render Quantum Learning Stack

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: drawio-export-${{ github.ref }}
  cancel-in-progress: true

jobs:
  render_tests:
    runs-on: ubuntu-latest
    name: Building Quantum Stack!
    steps:
      - uses: actions/checkout@v2
      - name: Initiating entanglement
        run: echo Building Quantum Stack!

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y_T%H:%M:%S')"

      # png
      - name: Building png
        uses: Burnett01/actions-drawio@1.1
        with:
          src: quantum_roadmap.drawio
          dest: images/quantum_roadmap.png
      #svg
      - name: Building svg
        uses: Burnett01/actions-drawio@1.1
        with:
          src: quantum_roadmap.drawio
          dest: images/quantum_roadmap.svg

      - name: Changelog
        run: |
          echo 'Generating new images at ${{ steps.date.outputs.date }}' >> changelog.txt

    # Upload files to repo
      - name: List & upload rendered files
        run: 'ls -l ${{ steps.render.outputs.rendered-files }}'
      - uses: EndBug/add-and-commit@v7
        with:
          message: "[PMF Bot] Updated png!"
          author_name: PMF Github Bot
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          add: "*.*"

      # Upload Artifacts
      - name: Upload png as artifact
        uses: actions/upload-artifact@v1
        with:
          name: png
          path: images/quantum_roadmap.png

      - name: Upload svg as artifact
        uses: actions/upload-artifact@v1
        with:
          name: svg
          path: images/quantum_roadmap.svg

      - name: Collapsing Quantum states
        run: echo Finished workflow!
