# This is a basic workflow to help you get started with Actions
# Based on: https://github.com/racklet/render-drawio-action

name: Render Quantum Learning Stack

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  render_drawio:
    runs-on: ubuntu-latest
    name: Render draw.io files
    steps:      
    - name: Checkout
      uses: actions/checkout@v2
    
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Building Quantum Stack!
      
    - name: Render draw.io files
      uses: docker://ghcr.io/racklet/render-drawio-action:v1.0.3
      id: render
      with: 
        # Showcasing the default values here
        formats: 'svg','pdf','png'
        sub-dirs: '.'
        skip-dirs: '.git'
        # files: '' # unset, specify "dest-file:src-file" mappings here
        log-level: 'info'
    - name: List the rendered files
      run: 'ls -l ${{ steps.render.outputs.rendered-files }}'
    - uses: EndBug/add-and-commit@v7
      with:
        # This "special" author name and email will show up as the GH Actions user/bot in the UI
        author_name: pmf-github-action
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'Automatically rendered .drawio files for quantum learning stack'
        add: "${{ steps.render.outputs.rendered-files }}"
      if: "${{ steps.render.outputs.rendered-files != ''}}"
